create table flyway_schema_history
(
    installed_rank integer                 not null
        constraint flyway_schema_history_pk
            primary key,
    version        varchar(50),
    description    varchar(200)            not null,
    type           varchar(20)             not null,
    script         varchar(1000)           not null,
    checksum       integer,
    installed_by   varchar(100)            not null,
    installed_on   timestamp default now() not null,
    execution_time integer                 not null,
    success        boolean                 not null
);

alter table flyway_schema_history
    owner to handy;

create index flyway_schema_history_s_idx
    on flyway_schema_history (success);

create table departments
(
    created_at  timestamp(6),
    id          bigint generated by default as identity
        primary key,
    manager_id  bigint,
    updated_at  timestamp(6),
    description varchar(255),
    name        varchar(255) not null
        unique
);

alter table departments
    owner to handy;

create table users
(
    enabled                     boolean      not null,
    activation_token_expiry     timestamp(6),
    created_at                  timestamp(6),
    id                          bigint generated by default as identity
        primary key,
    reset_password_token_expiry timestamp(6),
    verification_token_expiry   timestamp(6),
    version                     bigint,
    activation_token_hash       varchar(255),
    email                       varchar(255) not null
        unique,
    password                    varchar(255),
    reset_password_token_hash   varchar(255),
    role                        varchar(255) not null
        constraint users_role_check
            check ((role)::text = ANY
                   ((ARRAY ['ADMIN'::character varying, 'MANAGER'::character varying, 'EMPLOYEE'::character varying])::text[])),
    verification_token_hash     varchar(255)
);

alter table users
    owner to handy;

create table employees
(
    birth_date                date,
    contract_end_date         date,
    contractual_hours_per_day numeric(38, 2) not null,
    deleted                   boolean        not null,
    expected_start_time       time(6)        not null,
    hire_date                 date,
    salary                    numeric(38, 2),
    archived_at               timestamp(6),
    created_at                timestamp(6),
    department_id             bigint
        constraint fkgy4qe3dnqrm3ktd76sxp7n4c2
            references departments,
    id                        bigint generated by default as identity
        primary key,
    manager_id                bigint
        constraint fki4365uo9af35g7jtbc2rteukt
            references employees,
    updated_at                timestamp(6),
    user_id                   bigint
        unique
        constraint fk69x3vjuy1t5p18a5llb8h2fjx
            references users,
    version                   bigint,
    email                     varchar(255)   not null
        unique,
    first_name                varchar(255)   not null,
    gender                    varchar(255)
        constraint employees_gender_check
            check ((gender)::text = ANY ((ARRAY ['MALE'::character varying, 'FEMALE'::character varying])::text[])),
    last_name                 varchar(255)   not null,
    phone                     varchar(255),
    photo_key                 varchar(255),
    position                  varchar(255),
    status                    varchar(255)
        constraint employees_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying, 'ARCHIVED'::character varying])::text[]))
);

alter table employees
    owner to handy;

create table attendance_records
(
    work_date      date         not null,
    worked_minutes integer,
    check_in_at    timestamp(6),
    check_out_at   timestamp(6),
    created_at     timestamp(6),
    employee_id    bigint       not null
        constraint fk9i546p78s8xmw82howmttgek8
            references employees,
    id             bigint generated by default as identity
        primary key,
    updated_at     timestamp(6),
    version        bigint,
    status         varchar(255) not null
        constraint attendance_records_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PRESENT'::character varying, 'LATE'::character varying, 'ABSENT'::character varying, 'ON_LEAVE'::character varying])::text[])),
    unique (employee_id, work_date)
);

alter table attendance_records
    owner to handy;

alter table departments
    add constraint fk56q3esufky8u69xbmo4n63c4r
        foreign key (manager_id) references employees;

create table leave_balances
(
    allocated_days integer      not null,
    used_days      integer      not null,
    year           integer      not null,
    employee_id    bigint       not null
        constraint fkmvepkwsegu6bt3ps5rfh1dx92
            references employees,
    id             bigint generated by default as identity
        primary key,
    version        bigint,
    leave_type     varchar(255) not null
        constraint leave_balances_leave_type_check
            check ((leave_type)::text = ANY
                   ((ARRAY ['ANNUAL'::character varying, 'SICK'::character varying, 'MATERNITY_PATERNITY'::character varying, 'UNPAID'::character varying])::text[])),
    unique (employee_id, leave_type, year)
);

alter table leave_balances
    owner to handy;

create table leave_requests
(
    end_date        date         not null,
    requested_days  integer      not null,
    start_date      date         not null,
    created_at      timestamp(6),
    employee_id     bigint       not null
        constraint fkrxff2xg1kffbjfh5maxwoqyhw
            references employees,
    id              bigint generated by default as identity
        primary key,
    reviewed_at     timestamp(6),
    reviewed_by_id  bigint
        constraint fkg9v2kn15gb6k7yu9v1cfh60pl
            references employees,
    updated_at      timestamp(6),
    version         bigint,
    manager_comment varchar(1000),
    reason          varchar(1000),
    leave_type      varchar(255) not null
        constraint leave_requests_leave_type_check
            check ((leave_type)::text = ANY
                   ((ARRAY ['ANNUAL'::character varying, 'SICK'::character varying, 'MATERNITY_PATERNITY'::character varying, 'UNPAID'::character varying])::text[])),
    status          varchar(255) not null
        constraint leave_requests_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[]))
);

alter table leave_requests
    owner to handy;

create table payslips
(
    base_salary              numeric(38, 2) not null,
    daily_rate               numeric(38, 2) not null,
    deduction_amount         numeric(38, 2) not null,
    month                    integer        not null,
    net_salary               numeric(38, 2) not null,
    unjustified_absence_days integer        not null,
    year                     integer        not null,
    employee_id              bigint         not null
        constraint fki2u90djkfkqooebb9b26gxqmi
            references employees,
    generated_at             timestamp(6),
    id                       bigint generated by default as identity
        primary key,
    version                  bigint,
    pdf_key                  varchar(255),
    status                   varchar(255)
        constraint payslips_status_check
            check ((status)::text = ANY
                   ((ARRAY ['GENERATED'::character varying, 'ARCHIVED'::character varying])::text[])),
    unique (employee_id, year, month, status)
);

alter table payslips
    owner to handy;


